### ISSUE TITLE
Error: Error while copying content to a stream.

### ISSUE THREAD

**Issue by FuryMartin** [JasonWei512/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release#3]
我在使用本 Action 时遇到了如题所示的错误，希望得到帮助。

## 我所发布的 Release 
https://github.com/FuryMartin/BUAA-SpocHelper/releases/tag/v1.0.12

## 我所使用的 Action yml：
```yml
# Download the latest MSIX packages from Microsoft Store and upload them to GitHub release.
# See: https://github.com/JasonWei512/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release

name: Upload store MSIX to release

on: 
  release:  
    types: [released]   # Run the action when a GitHub release is published

  schedule:
    - cron:  '0 */6 * * *'  # Run the action every 6 hours

  workflow_dispatch:    # Manually run the action

jobs:
  upload-store-msix-to-release:
    runs-on: ubuntu-latest

    steps:
    - name: Upload store MSIX to release
      uses: JasonWei512/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release@v1
      with:
        store-id: 9PM0GCZ6ZD53
        token: ${{ secrets.GITHUB_TOKEN }}
        asset-name-pattern: SpocHelper_{version}_{arch}
```

## 详细的 Run Log：
```
/usr/bin/docker run --name c04425dc3[7](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:8)fbc06ec4a[8](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:9)8ad[9](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:10)c4f727f62ed1d_97b868 --label 6c0442 --workdir /github/workspace --rm -e "INPUT_STORE-ID" -e "INPUT_TOKEN" -e "INPUT_ASSET-NAME-PATTERN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/BUAA-SpocHelper/BUAA-SpocHelper":"/github/workspace" 6c0442:5dc37fbc06ec4a88ad9c4f727f62ed1d  "--store-id" "9PM0GCZ6ZD53" "--token" "***" "--asset-name-pattern" "SpocHelper_{version}_{arch}"
Getting info of app with ID "9PM0GCZ6ZD53" from Microsoft Store ...
Found app: Spoc Helper

Getting app package list ...
The latest app version is: 1.0.12.0
Found 2 packages: x86, x64

Found GitHub release: v1.0.12
2 files to upload.

File to upload: SpocHelper_1.0.12.0_x86.Msix
Downloading x86 package from Microsoft Store ...
Progress:  00.00%  -      1 KB / 47.52 MB  -  0 b/s
Progress:  33.67%  -     16 MB / 47.52 MB  -  0 b/s
Progress:  33.67%  -     16 MB / 47.52 MB  -  5.45 MB/s
Progress:  50.51%  -     24 MB / 47.52 MB  -  5.45 MB/s
Progress:  50.51%  -     24 MB / 47.52 MB  -  3.7 MB/s
Progress: [10](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:11)0.00%  -  47.52 MB / 47.52 MB  -  3.7 MB/s
File downloaded to: /tmp/31700Y.Fan.SpocHelper_1.0.[12](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:13).0_x86__4r5xyf54ce42m.Msix
Uploading to GitHub release ...
Error: Error while copying content to a stream.

System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|[15](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:16)3_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.IO.Stream.<CopyToAsync>g__Core|27_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Octokit.Internal.HttpClientAdapter.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/Octokit/Http/HttpClientAdapter.cs:line [19](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:20)5
   at Octokit.Internal.HttpClientAdapter.Send(IRequest request, CancellationToken cancellationToken) in /_/Octokit/Http/HttpClientAdapter.cs:line 49
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /_/Octokit/Http/Connection.cs:line 695
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /_/Octokit/Http/Connection.cs:line 686
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /_/Octokit/Http/ApiConnection.cs:line [29](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:30)3
   at UploadMicrosoftStoreMsixPackageToGitHubRelease.GitHubHelper.UploadMsixPackagesToGitHubRelease(Release gitHubRelease, IEnumerable`1 msixPackages, String assetNamePattern, Boolean dryRun) in /build/UploadMicrosoftStoreMsixPackageToGitHubRelease/GitHubHelper.cs:line 80
   at Program.<<Main>$>g__Start|0_0(Options options) in /build/UploadMicrosoftStoreMsixPackageToGitHubRelease/Program.cs:line [39](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:40)
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in /build/UploadMicrosoftStoreMsixPackageToGitHubRelease/Program.cs:line [48](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592#step:3:49)
```

Action 运行的详情您也可以在 [这里](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4697871333/jobs/8329523592) 查看

## 详细操作步骤
1. 在 repo 中添加本 action
2. 创建 Release，Tag为 `v1.0.12` （与商店保持一致）
3. Action 在 Release 创建后自动运行，运行失败

**Comment by FuryMartin** [comment]
已解决：问题出在仓库的权限上

将仓库的 Settings -> Actions -> General 中的 Workflow permissions 改为 `Read and write permissions` 即可

**Comment by JasonWei512** [comment]
我更新了 README，提到了这个问题。
感谢你的反馈。
